server:
  port: 8080

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productDb
#    url: jdbc:mysql://localhost:3306/productDb
    username: root
    password: Dipak@11
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296
# eureka Client Configuration

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER-ADDRESS:http://localhost:8761/eureka}
